### PR TITLE
Minor fix and performance improvement

### PR DESCRIPTION
**Pull request by jdleesmiller**
Thanks for creating this gem! I've mentioned it on https://github.com/rails/rails/issues/29893 as a workaround for the host injection problem with rails on heroku.

I've suggested a few minor fixes in this PR:

1. One of the headers was listed twice, so remove the duplicate.

2. I ran some benchmarks, and the `env.method(:delete)` does introduce some overhead compared to a normal `each` loop:
   ```rb
   require 'benchmark'
   remove_headers = ["HTTP_X_FORWARDED_HOST", "HTTP_X_FORWARDED_PORT", "HTTP_X_FORWARDED_SCHEME", "HTTP_X_FORWARDED_SSL"]
   env = {} 
   n = 1_000_000
   Benchmark.bm(7) do |x|
     x.report("method:"){ n.times do ; remove_headers.each(&env.method(:delete)); end }
     x.report("plain:") { n.times do ; remove_headers.each do |k| env.delete(k); end; end }
   end
   ```
   ```
                 user     system      total        real
   method:   1.240000   0.010000   1.250000 (  1.263514)
   plain:    0.340000   0.000000   0.340000 (  0.349208)
   ```
   (ruby 2.4 on a late 2016 MBP)

   It's not much, but given that this runs on every request, and that no clarity is lost, I'd be inclined to use the more efficient form.

3. I've also suggested using `Rack::Test` in the tests, which makes the test a bit more realistic, in the sense that we can set the header using it's actual name (instead of its env name) and verify that it gets removed.

HTH!

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]
LGTM!

**Comment by jdleesmiller** [comment]
Great! Would it be possible for you to also release a new gem version (0.0.2 I guess)?

**Comment by vivangkumar** [comment]
@jdleesmiller yup! Afraid I don't have much time till next week. I'll do so on Monday :) Thanks for the PR.

**Pull request merged**
